# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: platform/v1/entities.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'platform/v1/entities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aplatform/v1/entities.proto\x12\x10\x63ore.platform.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x01\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x33\n\x0f\x65nrollment_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"j\n\x07Vacancy\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12/\n\x0bposted_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xac\x01\n\x0b\x41pplication\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nstudent_id\x18\x02 \x01(\x03\x12\x12\n\nvacancy_id\x18\x03 \x01(\x03\x12\x34\n\x10\x61pplication_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x06status\x18\x05 \x01(\x0e\x32#.core.platform.v1.ApplicationStatus*n\n\x11\x41pplicationStatus\x12\"\n\x1e\x41PPLICATION_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07PENDING\x10\x01\x12\x0c\n\x08REVIEWED\x10\x02\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x03\x12\x0c\n\x08REJECTED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform.v1.entities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATIONSTATUS']._serialized_start=495
  _globals['_APPLICATIONSTATUS']._serialized_end=605
  _globals['_STUDENT']._serialized_start=82
  _globals['_STUDENT']._serialized_end=210
  _globals['_VACANCY']._serialized_start=212
  _globals['_VACANCY']._serialized_end=318
  _globals['_APPLICATION']._serialized_start=321
  _globals['_APPLICATION']._serialized_end=493
# @@protoc_insertion_point(module_scope)
