# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: platform/v1/events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'platform/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from platform.v1 import entities_pb2 as platform_dot_v1_dot_entities__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18platform/v1/events.proto\x12\x10\x63ore.platform.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aplatform/v1/entities.proto\"y\n\tBaseEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.core.platform.v1.EventType\x12/\n\x0boccurred_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x84\x01\n\x17\x41pplicationCreatedEvent\x12)\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x1b.core.platform.v1.BaseEvent\x12\x16\n\x0e\x61pplication_id\x18\x02 \x01(\x03\x12\x12\n\nstudent_id\x18\x03 \x01(\x03\x12\x12\n\nvacancy_id\x18\x04 \x01(\x03\"\xd4\x01\n\x1d\x41pplicationStatusChangedEvent\x12)\n\x04\x62\x61se\x18\x01 \x01(\x0b\x32\x1b.core.platform.v1.BaseEvent\x12\x16\n\x0e\x61pplication_id\x18\x02 \x01(\x03\x12\x37\n\nold_status\x18\x03 \x01(\x0e\x32#.core.platform.v1.ApplicationStatus\x12\x37\n\nnew_status\x18\x04 \x01(\x0e\x32#.core.platform.v1.ApplicationStatus*\x8c\x01\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12STUDENT_REGISTERED\x10\x01\x12\x12\n\x0eVACANCY_POSTED\x10\x02\x12\x17\n\x13\x41PPLICATION_CREATED\x10\x03\x12\x1e\n\x1a\x41PPLICATION_STATUS_CHANGED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=581
  _globals['_EVENTTYPE']._serialized_end=721
  _globals['_BASEEVENT']._serialized_start=107
  _globals['_BASEEVENT']._serialized_end=228
  _globals['_APPLICATIONCREATEDEVENT']._serialized_start=231
  _globals['_APPLICATIONCREATEDEVENT']._serialized_end=363
  _globals['_APPLICATIONSTATUSCHANGEDEVENT']._serialized_start=366
  _globals['_APPLICATIONSTATUSCHANGEDEVENT']._serialized_end=578
# @@protoc_insertion_point(module_scope)
